# Copyright 2024 Dan Cassidy

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later


# script used for sanitizing the FOMOD XMLs as generated by the FOMOD Creation Tool

param (
    [string] $FOMODPath = ".\data\fomod"
)

$ErrorActionPreference = "Stop"

$fomod_xml_files = @("info.xml", "ModuleConfig.xml")

$fomod_xml_files | ForEach-Object {
    $file = Join-Path $FOMODPath $_

    Write-Host "Sanitizing `"$file`": " -NoNewline

    if (-not (Test-Path $file)) {
        Write-Warning "Not Found"
        return
    }

    # load contents of file
    $content = Get-Content -Path $file

    # remove trailing spaces
    $content = $content -replace '\s+$', ''

    # remove "&#13;&#10;"
    $content = $content -replace '&#13;&#10;', ''

    # save file as UTF-16 LE
    Set-Content -Path $file -Value $content -Encoding Unicode

    Write-Host "Sanitized"
}
